### PR TITLE
Finish UI flow

### PR DESCRIPTION
**Pull request by JocelynYH**
This PR completes all the components with animations for RadGab!!  Game is now completely playable, sans the addition of tooltips/rules. 

The following issues are completed with the merge of this PR:
https://github.com/bgreenawald/madgab-online/issues/14
https://github.com/bgreenawald/madgab-online/issues/13
https://github.com/bgreenawald/madgab-online/issues/11

In addition, a couple random bugs are taken care of, most of which are related to minimizing several web socket instances into one shared reference, or are related to rendering at the appropriate time after waiting for server responses, ex:
Waiting component was trying to render before it got data back. 
Minor css tweaks

One thing I am concerned about is whether or not the animation library used (gsap) will cause any performance issues - ex: slowness or a computer's fan to kick in?  

I showed a coworker gsap example projects, and he said his fan kicked in.  I've been noticing my fan doing the same recently, but I'm not sure if it's related to the animations. **Update: I kicked all my local servers, and the fans are still going, so I don't think gsap is the cause.

### CODE REVIEW

**Comment by bgreenawald** [comment]
Do you have any idea how the potential performance issues you indicated may affect mobile devices?

**Comment by bgreenawald** [comment]
Also is GSAP not something we can install with the rest of the node modules?

**Comment by JocelynYH** [comment]
> Also is GSAP not something we can install with the rest of the node modules?

For the core GSAP package yes, but for the physics engine, that was a local package I had to manually install.

**Comment by JocelynYH** [comment]
> Do you have any idea how the potential performance issues you indicated may affect mobile devices?

I did some googling, and if we run into performance issues on mobile, looks like there are some easy fixes.  


I think our best bet would be to test the performance ourselves and see the results - or perhaps add analytics to track performance.

**Comment by bgreenawald** [comment]
This looks great! I don't know why I'm surprised but it just feels so legit. I had to remove SCSS from the backend (b3e570a) but other than that, my tests were running fine.

I didn't play through a whole game but I did a couple of rounds and everything ran smoothly. I only noticed one issue #27, but I think if that get's fixed, you're good to merge!

**Comment by JocelynYH** [comment]
Sweeeet, sounds good -  I'll fix that.  that was a good catch - thanks!

**Comment by JocelynYH** [comment]
I'm resolving merge conflicts - do you want the commented out code in actions.js?

**Comment by bgreenawald** [comment]
I don't think I touched that file so any commented code should be yours.

**Comment by JocelynYH** [comment]
ah you're right my b

**Pull request merged**
